### ISSUE TITLE
What is switchboard?

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry-incubator/switchboard#1]
I know we have Gorouter and Diego has some sort of routing logic. What role does switchboard fulfill?

**Comment by robdimsdale** [comment]
I don't know what happened to that story as I get a 'Not Allowed' when I try to view it. Anyway, to briefly answer your question (as I'm sure we will provide a fuller answer in time via README or something similar) we have a requirement that if a client makes a TCP connection to a backend via a proxy, and the backend becomes unhealthy but it still accessible, that we sever the connection. No existing solution (HAProxy, Nginx etc) provides this functionality.

Many proxies are designed with HTTP in mind, which tends to produce a solution where connection-severing isn't relevant because connections are always short-lived, and new connections will get routed to a healthy backend, effectively draining the unhealthy backend as connections naturally close.

It isn't intended to replace any existing CF components; it is currently used only as the proxy-tier in front of the mysql/mariadb backends in cf-mysql-release (and at the time of writing is not yet in production).

**Comment by drnic** [comment]
Do you remember why you wanted to sever the TCP connection with the client, rather than maintain it and hold incoming requests until new master is available?

**Comment by drnic** [comment]
Could this feature have been added into haproxy and/or nginx rather than a new CF component?

**Comment by robdimsdale** [comment]
We wish to sever the connection, so the client will be forced to reconnect, and that will enable them to be routed to a healthy backend. Maintaining connections and transparently failing over to a new backend would require semantic knowledge of what the connection contains, what state it is in etc. This is significantly more complex then severing the connection.

From the client's perspective it looks like it is connected to a single backend, that backend briefly disappears and is immediately available again.

We evaluated adding this feature as a plugin to haproxy and nginx but it was deemed easier to create this project. There are no existing CF components that could provide this functionality. If CF router supported TCP it might have been an option to add this functionality to that component.

**Comment by drnic** [comment]
Yeah I can imagine ugly edge cases - mid-stream in a sequence of commands within a transaction etc.

**Comment by robdimsdale** [comment]
Exactly. There's probably also performance costs associated with parsing the data in the proxy.

**Comment by shalako** [comment]
I think this can be closed. I enhanced the README, pointing to the develop branch of docs in cf-mysql-release.
