### ISSUE TITLE
Switchboard should expose a port for non-primary nodes

### ISSUE THREAD

**Issue by Freakin** [cloudfoundry-incubator/switchboard#13]
We have several larger CF installations (2500 spaces, 15000 apps), and period scraping of CAPI for metadata to power logging and telemetry causes significant performance impact due to the load on the primary DB node.

It would be great if I could configure a set of read-only CAPI nodes pointed at a separate port on switchboard which directs to the non-primary nodes.  I could then register these CAPI nodes to a new route like `reporting-api.<system domain>` and use this for my telemetry queries.

**Comment by menicosia** [comment]
Hi there @Freakin, sorry for the delayed response.

It turns out we have done this feature, it's implemented and distributed in [pxc-release v0.11.0](https://github.com/cloudfoundry-incubator/pxc-release/releases/tag/v0.11.0). Read more in the story: [#158778252](https://www.pivotaltracker.com/n/projects/969486/stories/158778252)

Please let us know what you think! I'll close this issue for now, but please feel free to re-open or send us feedback.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.
