### ISSUE TITLE
Discover master from etcd/consul?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/switchboard#8]
I have a feeling that switchboard is designed only for master-master clusters where switchboard is responsible for master selection.

In our PG cluster system we are orchestrating the master selection and promotion; we just want to communicate the new master/leader to the TCP routing layer and have it sever client connections to force them to reconnect. Possible?

**Comment by menicosia** [comment]
Hi @drnic,

Right now, Switchboard is a simple project with plenty of potential. You're right that it's designed to independently choose amongst a set of masters. It doesn't have any concept of who might be promoted from slave to master.

Part of this is because we wanted switchboard's failover to be **fast**. So it monitors the health of all masters, and when a master starts to fail, it very aggressively cuts connections and start routing new connections to a different master.

This is sort of a limitation today, in that we can't have a horizontally scalable tier of switchboards. In the case of MySQL multi-master, you want all read/write queries to go to the same master, else suffer the small possibility of deadlocks. Switchboard doesn't sync its decision of who the new master is, so it's possible that independent switchboards will choose different masters. Thus, we direct everyone who implements cf-mysql-release to add an additional Load Balancer in failover mode above switchboard.

This is something we plan to address. We haven't decided if we want to put more effort into switchboard right now - we are going to investigate [MaxScale](https://mariadb.com/products/mariadb-maxscale) as a better solution for cf-mysql-release.

Even if we go with MaxScale, though, switchboard's a neat little project that's probably worth further investment, assuming it fits some valuable use cases.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by menicosia** [comment]
Hi @drnic,

I think I'm going to go ahead and close this issue for now. Of course, feel free to re-open any time.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
